"""empty message

Revision ID: 172479382a1f
Revises: 1eede39aba3d
Create Date: 2024-03-11 10:17:21.526246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172479382a1f'
down_revision = '1eede39aba3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_picture',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('imageType', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('uploadTime', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('medicalImage', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_picture')
    # ### end Alembic commands ###
