"""empty message

Revision ID: 17f39e3cb23b
Revises: 61dd29996f70
Create Date: 2024-03-27 13:24:12.950109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17f39e3cb23b'
down_revision = '61dd29996f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserMessage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('userHead', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('asset', sa.String(length=255), nullable=False),
    sa.Column('idCard', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idCard')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idCard')
        batch_op.drop_index('ix_user_age')
        batch_op.drop_index('ix_user_name')
        batch_op.drop_column('idCard')
        batch_op.drop_column('name')
        batch_op.drop_column('userHead')
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('userHead', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('idCard', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_user_name', ['name'], unique=False)
        batch_op.create_index('ix_user_age', ['age'], unique=False)
        batch_op.create_index('idCard', ['idCard'], unique=True)

    op.drop_table('UserMessage')
    # ### end Alembic commands ###
