"""empty message

Revision ID: 1eede39aba3d
Revises: 663aac64fb3f
Create Date: 2024-03-04 17:12:36.788365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eede39aba3d'
down_revision = '663aac64fb3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userHead', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['userHead'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('userHead')

    # ### end Alembic commands ###
