"""empty message

Revision ID: 61dd29996f70
Revises: 6cd19e3d5c5f
Create Date: 2024-03-25 18:36:13.170912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61dd29996f70'
down_revision = '6cd19e3d5c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modal_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modal_list', schema=None) as batch_op:
        batch_op.drop_column('image_time')

    # ### end Alembic commands ###
