"""empty message

Revision ID: cafa4f43f9b7
Revises: c0573d3e564c
Create Date: 2024-04-06 17:21:13.201116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cafa4f43f9b7'
down_revision = 'c0573d3e564c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
