data_root: inference_model/submit/

batch_size: 2
iters: 30000

model:
  type: NNUNet
  plan_path: inference_model/nnUNetPlansv2.1_plans_3D.pkl
  stage: 0
  cascade: True

train_dataset:
  type: MSDDataset
  plans_name: nnUNetPlansv2.1_plans_3D.pkl
  dataset_root: /
  result_dir: /
  raw_data_dir: inference_model/data
  decathlon_dir: inference_model/data
  cropped_data_dir: inference_model/data
  preprocessed_dir: inference_model/data
  plan2d: False
  plan3d: True
  result_dir: /
  raw_data_dir: inference_model/data
  decathlon_dir: inference_model/data
  cropped_data_dir: inference_model/data
  preprocessed_dir: inference_model/data
  plan2d: False
  plan3d: True
  num_batches_per_epoch: 250
  fold: 2
  stage: 0
  unpack_data: True
  cascade: True
  mode: train

val_dataset:
  type: MSDDataset
  plans_name: nnUNetPlansv2.1_plans_3D.pkl
  dataset_root: /
  result_dir: /
  raw_data_dir: inference_model/data
  decathlon_dir: inference_model/data
  cropped_data_dir: inference_model/data
  preprocessed_dir: inference_model/data
  num_batches_per_epoch: 50
  fold: 2
  stage: 0
  plan2d: False
  plan3d: True
  unpack_data: True
  cascade: True
  mode: val


optimizer:
  type: sgd
  momentum: 0.99
  weight_decay: 0.00003
  use_nesterov: True


lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.0099
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MultipleLoss
      plan_path: inference_model/nnUNetPlansv2.1_plans_3D.pkl
      stage: 0
      losses:
        - type: DC_and_CE_loss
          do_bg: False
          batch_dice: False
      coef: [1.0]
  coef: [1]
